backend:
  name: github
  repo: nazwhale/who-is-naz

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["coding"]

  - name: stuff
    label: Stuff
    folder: content/stuff
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: link, label: Link }
