backend:
  name: github
  repo: nazwhale/from-the-ceo

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: featured_image_url, label: Featured Image URL }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["shareholders"]
